#!/bin/sh

# Cachebuffer is a simple script to mount the cache
# partition and bind it to xbmc's temp directory.
# Written on 08/30/2013 by croniccorey @xda

OLD_CACHE=/root/.xbmc
NEW_CACHE=/tmp/cache/.xbmc

# Mount the cache partition on /tmp/cache
if [ ! -e /tmp/cache ]
then
  mkdir /tmp/cache;
fi;
  mount -t ext4 /dev/cache /tmp/cache;

# Create /root/.xbmc/temp if its not there already
if [ ! -e $OLD_CACHE/temp ]
then
  mkdir -p $OLD_CACHE/temp;
  chown -R root:root $OLD_CACHE;
  chmod -R 755 $OLD_CACHE;
fi;

# Bind /tmp/cache/.xbmc/temp to /root/.xbmc/temp
if [ ! -e $NEW_CACHE ]
then
  mkdir -p $NEW_CACHE/temp;
  cp -R $OLD_CACHE/temp/* $NEW_CACHE/temp;
  chown -R root:root $NEW_CACHE;
  chmod -R 755 $NEW_CACHE;
fi;
  mount -o bind $NEW_CACHE/temp $OLD_CACHE/temp;

sync;
